### ISSUE TITLE
Filter task on task text

### ISSUE THREAD

**Issue by DanielTitkov** [vran-dev/obsidian-contribution-graph#101]
I want to use this plugin instead of tracker plugin with my daily routine tasks, which look like this:
`- [ ] Do something`

It would be nice to have an option to filter tasks based on text (like all which have text == "Do something"), like i can do in tracker plugin. Currently it looks like i can filter tasks only buy tags, but i don't want to create several additional tags for this purpose. 

![image](https://github.com/user-attachments/assets/309324b9-73d0-4038-8913-71d2a35f85b6)

![image](https://github.com/user-attachments/assets/32f35848-b7b1-4ab6-a038-7550e8a6ec9b)

How tracker does it:

```yaml
searchType: task.done
searchTarget: Журнал
datasetName: Журнал
folder: JOURNAL/DAILY
startDate: -3M
fixedScale: 1
month:
	color: hsl(252, 84%, 83%)
```
