### ISSUE TITLE
How to center the heat map title?

### ISSUE THREAD

**Issue by Leiyi548** [vran-dev/obsidian-contribution-graph#13]
![image](https://github.com/vran-dev/obsidian-contribution-graph/assets/76139422/2fccd137-8e84-4a6d-8b5a-35b27a831eda)

**Comment by vran-dev** [comment]
There is no direct configuration item yet, but you can add [obsidian CSS snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets) to change the title to the center

```css
.contribution-graph .main .title {
  text-align: center;
}
```
