### ISSUE TITLE
Date is in the incorrect position or number of days in the month are off

### ISSUE THREAD

**Issue by Zolo805** [vran-dev/obsidian-contribution-graph#91]
Sorry for so many changes, trying to solve the issue and seeing that I am not writing my issue clearly. 

I am having a couple of issues. The first is that the number of days in the months is off by one. It also seems like the indexing of when the addon is reading the note is off by 1. The week should start with a Monday, also this month starts on a Monday, but it seems like it is putting it in Sunday first. I am not sure why the GIT look has that extra box starting on the bottom left Saturday. 

![Screenshot 2024-07-05 101925](https://github.com/vran-dev/obsidian-contribution-graph/assets/174821104/f2b03a3e-46ea-434e-9a32-fb9250f10937)
![Screenshot 2024-07-05 095721](https://github.com/vran-dev/obsidian-contribution-graph/assets/174821104/0567c3ee-dbbd-4f91-87f6-11edc8198e2b)

**Comment by vran-dev** [comment]
Hi,  show me your raw code or setting page

**Comment by shipmadison** [comment]
I just started using your plugin, and I'm also experiencing a date indexing issue. The day of the week is off by one. For example, Monday, 7/15/2024 is reading as Sunday in the heatmap. I've attached a screenshot and my code.  Thanks in advance! Other than this issue, love the plugin.

![image](https://github.com/user-attachments/assets/7f40c33e-d287-44e0-b6d3-927f51e2d701)

![image](https://github.com/user-attachments/assets/f520a15d-6a23-4941-9a0a-667e77206d39)

```contributionGraph
title: Energy
graphType: default
dateRangeValue: 90
dateRangeType: LATEST_DAYS
startOfWeek: "0"
showCellRuleIndicators: true
titleStyle:
  textAlign: center
  fontSize: 15px
  fontWeight: normal
dataSource:
  type: PAGE
  value: "#daily"
  dateField:
    type: PAGE_PROPERTY
    value: date
  countField:
    type: PAGE_PROPERTY
    value: energy
fillTheScreen: false
enableMainContainerShadow: false
cellStyleRules:
  - id: Halloween_d
    color: "#d94e49"
    min: "1"
    max: "2"
  - id: Halloween_c
    color: "#f07c44"
    min: 3
    max: 5
  - id: Halloween_b
    color: "#faaa53"
    min: "5"
    max: "7"
  - id: Halloween_a
    color: "#fdd577"
    min: "7"
    max: "999"

```

**Comment by Araxiel** [comment]
I also noticed the same issue.

![image](https://github.com/user-attachments/assets/a84ba1c2-53df-41f4-b303-5b1961fa2906)

```
contributionGraph
title: Contributions
graphType: month-track
dateRangeValue: 7
dateRangeType: LATEST_DAYS
startOfWeek: 0
showCellRuleIndicators: true
titleStyle:
  textAlign: left
  fontSize: 15px
  fontWeight: normal
dataSource:
  type: PAGE
  value: ""
  dateField: {}
fillTheScreen: false
enableMainContainerShadow: false
cellStyleRules: []

```

The type of view or first day of the week doesn't seem to matter, it's always a day off.
If you need any additional info, I'm more than willing to help.
